apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ${APP_NAME}-servicemonitor
  name: ${APP_NAME}-servicemonitor
  namespace: ${NAMESPACE}
spec:
  endpoints:
    - interval: 30s
      port: 8080-tcp
      scheme: http
      # HTTP path to scrape for metrics
      # path: ""
      # Timeout after which the scrape is ended
      # scrapeTimeout:
      relabelings:
        # - action: replace
        #   regex: (.*)
        #   replacement: $1
        #   separator: ;
        #   sourceLabels:
        #     - __meta_kubernetes_namespace
        #   targetLabel: namespace
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: kubernetes_namespace
  # podTargetLabels:
  #   - kubernetes_namespace
  selector:
    matchLabels:
      app: ${APP_NAME}
  targetLabels:
    - app
