namespaceScope: false
leaderElect: false
watchNamespaces: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: "appmon"

isOpenshift: true

serviceAccount:
  create: true
  annotations: {}
  name: "appmon-serviceaccount"

metricsService:
  type: ClusterIP
  metricsPort: 9090

additionalLabels:
  app: appmon-dedalus

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources: {}

priorityClassName: ""

nodeSelector: {}

tolerations: []

affinity: {}
