apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  # For AllNamespaces install mode usage, specify the 'openshift-operators' namespace.
  # Otherwise, specify the relevant single namespace for SingleNamespace install mode usage.
  # look for installModes by command: 'oc get packagemanifests grafana-operator -o yaml'
  namespace: test-monitoring
spec:
  # Name of the channel to subscribe to.
  # look for the channel version available by command: 'oc get packagemanifests grafana-operator -o yaml'
  channel: v4
  # Set the approval strategy to Manual in case your specified version is superseded by a later version in the catalog.
  # This plan prevents an automatic upgrade to a later version and requires manual approval before the starting CSV can complete the installation.
  installPlanApproval: Automatic
  # Name of the Operator to subscribe to
  name: grafana-operator
  # Name of the catalog source that provides the Operator.
  # you can choose among 'redhat-operators' and 'community-operators'
  source: community-operators
  # Namespace of the catalog source. Use openshift-marketplace for the default OperatorHub catalog sources.
  sourceNamespace: openshift-marketplace
  # Set a specific version of an Operator CSV
  startingCSV: grafana-operator.v4.2.0
  config:
    # env: 
    # - name: ARGS
    #   value: "-v=10"
    # envFrom: 
    # - secretRef:
    #     name: license-secret
    # volumes: 
    # - name: <volume_name>
    #   configMap:
    #     name: <configmap_name>
    # volumeMounts: 
    # - mountPath: <directory_name>
    #   name: <volume_name>
    # tolerations: 
    # - operator: "Exists"
    resources: 
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    # The nodeSelector parameter defines a NodeSelector for the pod created by OLM
    # nodeSelector: 
    #   foo: bar