apiVersion: v1
items:
- apiVersion: integreatly.org/v1alpha1
  kind: Grafana
  metadata:
    name: dedalus-grafana
    namespace: test-monitoring
  spec:
    config: {}
    dashboardLabelSelector:
    - matchExpressions:
      - key: app
        operator: In
        values:
        - grafana
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 50m
        memory: 200Mi