apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-binding
subjects:
  - kind: ServiceAccount
    namespace: openshift-monitoring-dedalus
    name: grafana-serviceaccount
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: openshift-monitoring-dedalus
roleRef:
  kind: ClusterRole
  name: grafana-proxy
