apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana-persistent-oauth
  labels:
    app: grafana-dedalus
spec:
  client:
    preferService: true
  config:
    auth:
      disable_login_form: false
      disable_signout_menu: false
    auth.anonymous:
      enabled: true
    auth.basic:
      enabled: true
    auth.proxy:
      enable_login_token: true
      enabled: true
      header_name: X-Forwarded-User
      header_property: username
    log:
      level: warn
      mode: console
    # security:
    #   admin_password: admin
    #   admin_user: admin
  configMaps:
    - ocp-injected-certs
  containers:
  - args:
      - -provider=openshift
      - -pass-basic-auth=false
      - -https-address=:9091
      - -http-address=
      - -email-domain=*
      - -upstream=http://localhost:3000
      - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
      - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
      - -tls-cert=/etc/tls/private/tls.crt
      - -tls-key=/etc/tls/private/tls.key
      - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
      - -cookie-secret-file=/etc/proxy/secrets/session_secret
      - -openshift-service-account=grafana-serviceaccount
      - -openshift-ca=/etc/pki/tls/cert.pem
      - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      - -openshift-ca=/etc/grafana-configmaps/ocp-injected-certs/ca-bundle.crt
      - -skip-auth-regex=^/metrics
    image: quay.io/openshift/origin-oauth-proxy
    name: grafana-proxy
    ports:
      - containerPort: 9091
        name: https
        protocol: TCP
    resources: {}
    volumeMounts:
      - mountPath: /etc/tls/private
        name: secret-grafana-tls
        readOnly: false
      - mountPath: /etc/proxy/secrets
        name: secret-grafana-proxy
        readOnly: false
  dataStorage:
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  dashboardLabelSelector:
    - matchExpressions:
      - key: app
        operator: In
        values:
        - grafana-dedalus
  # ingress:
  #   annotations:
  #     service.beta.openshift.io/serving-cert-secret-name: grafana-tls
  #   enabled: true
  #   targetPort: https
  #   termination: reencrypt
  resources:
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 200Mi
  secrets:
    - grafana-tls
    - grafana-proxy
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: grafana-tls
    ports:
      - name: https
        port: 9091
        protocol: TCP
        targetPort: https
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-access"}}'
